version: '{build}'
branches:
  # whitelist
  only:
    - master
    - dev
image: 
  - Visual Studio 2019
  - Ubuntu

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - ./build.sh

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
  - ./build.ps1
 