version: '{build}'
branches:
  # whitelist
  only:
    - master
    - dev
image: 
  - Visual Studio 2019
  - Ubuntu

build_script:
- ps: |
    if ($isLinux) {
      build_script: ./build.sh
    } else {
      build_script: ./build.ps1
    }